# Set the Working Directory
setwd("?")

# When running different datasets, it is only necessary to replace the two files "result-1_p2.txt, gene_new_o.txt". 
#The file "power.txt" is generated by the following code.
# ------------------------power.txt---------------------------------------------------------
process_files <- function(gene_file='gene_new_o.txt', result_file='result-1_p2.txt') {

  gene_count <- length(readLines(gene_file))
  

  pairs <- do.call(rbind, lapply(strsplit(readLines(result_file), "\\s+"), 
                                 function(x) if(length(x)>=2) as.numeric(x[1:2]) else NULL))
  

  pairs_norm <- t(apply(pairs, 1, function(x) if(x[1]!=x[2] && x[1]>x[2]) x[2:1] else x))
  unique_pairs <- unique(pairs_norm)
  

  freq <- table(c(unique_pairs[,1], unique_pairs[unique_pairs[,1]!=unique_pairs[,2],2]))
  counts <- rep(0, gene_count)
  counts[as.numeric(names(freq))] <- as.numeric(freq)
  

  norm_val <- ifelse(counts>0, 1+(counts/max(counts)), 1)
  writeLines(as.character(norm_val), "power.txt")
}

process_files()
#------------------------结束，下面是正式的AWGE-ESPCA-----------------------------

result_1_p2_row <- length(readLines("result-1_p2.txt"))
gene_new_o <- read.delim("gene_new_o.txt", header = FALSE)
result.1_p2 <- read.table("result-1_p2.txt", quote = "\"", comment.char = "")
source('fun_AWGE.R')
n = 500
myString <- "start"
print(myString)
edges = list()
gene1 = data.matrix(gene_new_o)
gene = t(gene1)

for (i in 1:result_1_p2_row){
  edges[[i]] = c((result.1_p2[i,1]),(result.1_p2[i,2]))
}
out3 =  AWGE(gene, k = 2, edges, k.group=25,we=0, t = 0.1,niter=100)
myString <- "end!"
print(myString)

# Save U matrix to txt or csv file
write.table(out3$U, file = "U_matrix.txt", sep = "\t", quote = FALSE, row.names = FALSE)
# If you want to save U matrix to csv file, use this line instead
# write.csv(out3$U, file = "U_matrix.csv", row.names = FALSE)

# Save V matrix to txt or csv file
write.table(out3$V, file = "V_matrix.txt", sep = "\t", quote = FALSE, row.names = FALSE)
# If you want to save V matrix to csv file, use this line instead
# write.csv(out3$V, file = "V_matrix.csv", row.names = FALSE)

write.table(out3$D, file = "D_matrix.txt", sep = "\t", quote = FALSE, row.names = FALSE)



